//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamNotificationsTray.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Credentials {
            get {
                return ((string)(this["Credentials"]));
            }
            set {
                this["Credentials"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("92, 126, 16")]
        public global::System.Drawing.Color InboxAvailableColor {
            get {
                return ((global::System.Drawing.Color)(this["InboxAvailableColor"]));
            }
            set {
                this["InboxAvailableColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Color InboxNoneColor {
            get {
                return ((global::System.Drawing.Color)(this["InboxNoneColor"]));
            }
            set {
                this["InboxNoneColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("158, 194, 29")]
        public global::System.Drawing.Color InboxNewColor {
            get {
                return ((global::System.Drawing.Color)(this["InboxNewColor"]));
            }
            set {
                this["InboxNewColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int RefreshInterval {
            get {
                return ((int)(this["RefreshInterval"]));
            }
            set {
                this["RefreshInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("59, 57, 56")]
        public global::System.Drawing.Color NotificationPopupBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["NotificationPopupBackgroundColor"]));
            }
            set {
                this["NotificationPopupBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("130, 128, 124")]
        public global::System.Drawing.Color NotificationPopupBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["NotificationPopupBorderColor"]));
            }
            set {
                this["NotificationPopupBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("191, 191, 191")]
        public global::System.Drawing.Color NotificationInactiveColor {
            get {
                return ((global::System.Drawing.Color)(this["NotificationInactiveColor"]));
            }
            set {
                this["NotificationInactiveColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("33, 45, 61")]
        public global::System.Drawing.Color NotificationFocusColor {
            get {
                return ((global::System.Drawing.Color)(this["NotificationFocusColor"]));
            }
            set {
                this["NotificationFocusColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("112, 186, 36")]
        public global::System.Drawing.Color NotificationActiveColor {
            get {
                return ((global::System.Drawing.Color)(this["NotificationActiveColor"]));
            }
            set {
                this["NotificationActiveColor"] = value;
            }
        }
    }
}
