//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamNotificationsTray.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Credentials {
            get {
                return ((string)(this["Credentials"]));
            }
            set {
                this["Credentials"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("92, 126, 16")]
        public global::System.Drawing.Color InboxAvailableColor {
            get {
                return ((global::System.Drawing.Color)(this["InboxAvailableColor"]));
            }
            set {
                this["InboxAvailableColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Color InboxNoneColor {
            get {
                return ((global::System.Drawing.Color)(this["InboxNoneColor"]));
            }
            set {
                this["InboxNoneColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("158, 194, 29")]
        public global::System.Drawing.Color InboxNewColor {
            get {
                return ((global::System.Drawing.Color)(this["InboxNewColor"]));
            }
            set {
                this["InboxNewColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int RefreshInterval {
            get {
                return ((int)(this["RefreshInterval"]));
            }
            set {
                this["RefreshInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("59, 57, 56")]
        public global::System.Drawing.Color NotificationPopupBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["NotificationPopupBackgroundColor"]));
            }
            set {
                this["NotificationPopupBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("130, 128, 124")]
        public global::System.Drawing.Color NotificationPopupBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["NotificationPopupBorderColor"]));
            }
            set {
                this["NotificationPopupBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("191, 191, 191")]
        public global::System.Drawing.Color NotificationInactiveColor {
            get {
                return ((global::System.Drawing.Color)(this["NotificationInactiveColor"]));
            }
            set {
                this["NotificationInactiveColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("33, 45, 61")]
        public global::System.Drawing.Color NotificationFocusColor {
            get {
                return ((global::System.Drawing.Color)(this["NotificationFocusColor"]));
            }
            set {
                this["NotificationFocusColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("112, 186, 36")]
        public global::System.Drawing.Color NotificationActiveColor {
            get {
                return ((global::System.Drawing.Color)(this["NotificationActiveColor"]));
            }
            set {
                this["NotificationActiveColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("107, 104, 101")]
        public global::System.Drawing.Color NotificationPopupSeparatorColor {
            get {
                return ((global::System.Drawing.Color)(this["NotificationPopupSeparatorColor"]));
            }
            set {
                this["NotificationPopupSeparatorColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlwaysShowComments {
            get {
                return ((bool)(this["AlwaysShowComments"]));
            }
            set {
                this["AlwaysShowComments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlwaysShowItems {
            get {
                return ((bool)(this["AlwaysShowItems"]));
            }
            set {
                this["AlwaysShowItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlwaysShowInvites {
            get {
                return ((bool)(this["AlwaysShowInvites"]));
            }
            set {
                this["AlwaysShowInvites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlwaysShowGifts {
            get {
                return ((bool)(this["AlwaysShowGifts"]));
            }
            set {
                this["AlwaysShowGifts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysShowOfflineMessages {
            get {
                return ((bool)(this["AlwaysShowOfflineMessages"]));
            }
            set {
                this["AlwaysShowOfflineMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysShowTradeOffers {
            get {
                return ((bool)(this["AlwaysShowTradeOffers"]));
            }
            set {
                this["AlwaysShowTradeOffers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysShowAsyncGames {
            get {
                return ((bool)(this["AlwaysShowAsyncGames"]));
            }
            set {
                this["AlwaysShowAsyncGames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysShowModeratorMessages {
            get {
                return ((bool)(this["AlwaysShowModeratorMessages"]));
            }
            set {
                this["AlwaysShowModeratorMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysShowHelpRequestReplies {
            get {
                return ((bool)(this["AlwaysShowHelpRequestReplies"]));
            }
            set {
                this["AlwaysShowHelpRequestReplies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableBalloons {
            get {
                return ((bool)(this["EnableBalloons"]));
            }
            set {
                this["EnableBalloons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SingleIcon {
            get {
                return ((bool)(this["SingleIcon"]));
            }
            set {
                this["SingleIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysShowAccountAlerts {
            get {
                return ((bool)(this["AlwaysShowAccountAlerts"]));
            }
            set {
                this["AlwaysShowAccountAlerts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color NotificationCountColor {
            get {
                return ((global::System.Drawing.Color)(this["NotificationCountColor"]));
            }
            set {
                this["NotificationCountColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAntiFlapping {
            get {
                return ((bool)(this["EnableAntiFlapping"]));
            }
            set {
                this["EnableAntiFlapping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenLinksOnBalloonClick {
            get {
                return ((bool)(this["OpenLinksOnBalloonClick"]));
            }
            set {
                this["OpenLinksOnBalloonClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsUpgraded {
            get {
                return ((bool)(this["SettingsUpgraded"]));
            }
            set {
                this["SettingsUpgraded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSteamBrowserProtocolLinks {
            get {
                return ((bool)(this["UseSteamBrowserProtocolLinks"]));
            }
            set {
                this["UseSteamBrowserProtocolLinks"] = value;
            }
        }
    }
}
